wd: &wd
  working_directory: ~/vpp

php: &php
  docker:
    - image: circleci/php:7.2.19-cli

node: &node
  docker:
    - image: circleci/node:10.16.0

version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/buildpack-deps:18.04
    <<: *wd  
    steps:
      - checkout
      - save_cache:
          key: checkout-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/vpp

  php_checks:
    <<: *wd
    <<: *php
    steps:
      - restore_cache:
          key: checkout-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Check terminate scripts commands, and logs commands
          command: sh scripts/check_output.sh
      - run:
          name: Check git merged files
          command: sh scripts/check_merge.sh 
      - run:
          name: Check PHP Sintax()
          command: sh scripts/check_syntax.sh

  install_webpack:
      <<: *node
      <<: *wd
      steps:
        - restore_cache:
            key: checkout-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
        - run:
            name: Node as tooling install
            command: npm install
        - save_cache:
            key: dependency-cache-node-{{ checksum "package.json" }}
            paths:
              - node_modules

  build_webpack:
    <<: *node
    <<: *wd
    steps:
      - restore_cache:
          key: checkout-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}      
      - restore_cache:
          key: dependency-cache-node-{{ checksum "package.json" }}
      - run:
          name: Building public assets
          command: npm run prod
      - save_cache:
          key: public-assets-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - public/dist
  
  install_laravel:
    <<: *php
    <<: *wd
    steps:
      - restore_cache:
          key: checkout-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Laravel
          command: composer install                

workflows:
  version: 2
  build:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/
      - php_checks:
          requires:
            - checkout_code        
          filters:
            tags:
              only: /.*/              
      - install_webpack:
          requires:
            - checkout_code        
          filters:
            tags:
              only: /.*/
      - build_webpack:
          requires:
            - install_webpack        
          filters:
            tags:
              only: /.*/                 
      - install_laravel:
          requires:
            - checkout_code        
          filters:
            tags:
              only: /.*/                