
wd: &wd
  working_directory: ~/vpp

php: &php
  docker:
    - image: circleci/php:7.2.19-cli

version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/buildpack-deps:18.04
    <<: *wd  
    steps:
      - checkout
      - save_cache:
          key: checkout-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/vpp

  php_checks:
    <<: *wd
    <<: *php
    steps:
      - restore_cache:
          key: checkout-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Check terminate scripts commands, and logs commands
          command: |
            chmod +x scripts/check_output.sh
            sh scripts/check_output.sh
      - run:
          name: Check git merged files
          command: |
            chmod +x scripts/check_merge.sh
            sh scripts/check_output.sh 
      - run:
          name: Check PHP Sintax()
          command: |
            chmod +x scripts/check_syntax.sh
            sh scripts/check_output.sh 

workflows:
  version: 2
  build:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/
      - php_checks:
          requires:
            - checkout_code        
          filters:
            tags:
              only: /.*/              