
wd: &wd
  working_directory: ~/vpp

version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/buildpack-deps:18.04
    <<: *wd  
    steps:
      - checkout

workflows:
  version: 2
  build:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/