wd: &wd
  working_directory: ~/vpp

php: &php
  docker:
    - image: circleci/php:7.2.19-cli

node: &node
  docker:
    - image: circleci/node:10.16.0

ubuntu: &ubuntu
  docker:
    - image: circleci/buildpack-deps:18.04    

version: 2
jobs:
  checkout_code:
    <<: *ubuntu
    <<: *wd  
    steps:
      - checkout
      - save_cache:
          key: checkout-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/vpp

  php_checks:
    <<: *wd
    <<: *php
    steps:
      - restore_cache:
          key: checkout-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Check terminate scripts commands, and logs commands
          command: sh scripts/check_output.sh
      - run:
          name: Check git merged files
          command: sh scripts/check_merge.sh 
      - run:
          name: Check PHP Sintax()
          command: sh scripts/check_syntax.sh

  install_webpack:
      <<: *node
      <<: *wd
      steps:
        - restore_cache:
            key: checkout-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
        - run:
            name: Node as tooling install
            command: npm install
        - save_cache:
            key: dependency-cache-node-{{ checksum "package.json" }}
            paths:
              - node_modules

  build_webpack:
    <<: *node
    <<: *wd
    steps:
      - restore_cache:
          key: checkout-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}      
      - restore_cache:
          key: dependency-cache-node-{{ checksum "package.json" }}
      - run:
          name: Building public assets
          command: npm run prod
      - save_cache:
          key: public-assets-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - public/dist
  
  install_laravel:
    <<: *php
    <<: *wd
    steps:
      - restore_cache:
          key: checkout-cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install Laravel with Autoloader Optimization
          command: composer install --optimize-autoloader --no-dev
      - save_cache:
          key: laravel-install-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./      

  optimize_laravel:
    <<: *php
    <<: *wd
    steps:
      - restore_cache:
          key: laravel-install-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Optimizing Configuration Loading
          command: php artisan config:cache
      - run:
          name: Optimizing Route Loading
          command: php artisan route:cache
      - run:
          name: Optimizing Configuration Loading
          command: php artisan config:cache                    
      - save_cache:
          key: laravel-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./              

  build_targz:
    <<: *wd
    <<: *ubuntu
    steps:
      - restore_cache:
          key: laravel-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: public-assets-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Add new version.txt
          command: echo $CIRCLE_TAG-$(git rev-parse --short HEAD) >  ./_version.txt
      - run:
          name: Making build.tar.gz
          command: tar -zcvf build.tar.gz --exclude .circleci --exclude .env.* --exclude build.tar.gz --exclude-vcs build.tar.gz ./
      - store_artifacts:
          path: build.tar.gz
      - persist_to_workspace:
          root: ./
          paths:
            - build.tar.gz            

workflows:
  version: 2
  build:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/
      - php_checks:
          requires:
            - checkout_code        
          filters:
            tags:
              only: /.*/              
      - install_webpack:
          requires:
            - checkout_code        
          filters:
            tags:
              only: /.*/
      - build_webpack:
          requires:
            - install_webpack        
          filters:
            tags:
              only: /.*/                 
      - install_laravel:
          requires:
            - checkout_code        
          filters:
            tags:
              only: /.*/                
      - optimize_laravel:
          requires:
            - install_laravel        
          filters:
            tags:
              only: /.*/                   
      - build_targz:
          requires:
            - optimize_laravel
            - build_webpack     
          filters:
            tags:
              only: /.*/    